theme: jekyll-theme-midnight
title: ğŸ‘¨â€ğŸ’» JJ's Reference Architecture ğŸ›
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-seo
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
