theme: jekyll-theme-midnight
title: ğŸ› JJ's Reference Architecture ğŸ›
description: about software development techniques
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-seo
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
