theme: jekyll-theme-midnight
title: ğŸ“² JJ's Reference Architecture ğŸ§‘ğŸ½â€ğŸ’»
description: about software development techniques
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-seo
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md